### PR TITLE
Apply systemd restrictions to echobot

### PR DESCRIPTION
**Pull request by link2xt**
These options are suggested by
`systemd-analyze security echobot.service`

### CODE REVIEW

**Review by hpk42 — APPROVED** [review]
- please add the invocation that generated the settings as a comment atop. 
- please add changelog entry

**Comment by missytake** [comment]
`cmdeploy/src/cmdeploy/tests/online/test_2_deltachat.py::test_echobot` and `cmdeploy/src/cmdeploy/tests/test_cmdeploy.py::TestCmdline::test_parser ` seem to be timeouting?

**Comment by missytake** [comment]
it seems echo@staging.testrun.org doesn't exist:

`550 5.1.1 <echo@staging.testrun.org> User doesn't exist:
echo@staging.testrun.org (in reply to RCPT TO command)
`

**Comment by missytake** [comment]
`cmdeploy/src/cmdeploy/tests/test_cmdeploy.py::TestCmdline::test_parser` works locally at least.

**Pull request merged**
